{
 "title": "Export Data",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "query": "SELECT DISTINCT network FROM readings"
   },
   {
    "name": "node",
    "query": "SELECT DISTINCT node FROM readings WHERE network='$network'"
   },
   {
    "name": "device",
    "query": "SELECT DISTINCT device FROM readings WHERE network='$network' AND node='$node'"
   },
   {
    "name": "vargroup",
    "query": "SELECT DISTINCT vargroup FROM readings WHERE network='$network' AND node='$node' AND device='$device'"
   },
   {
    "name": "varkey",
    "query": "SELECT DISTINCT varkey FROM readings WHERE network='$network' AND node='$node' AND device='$device'  AND vargroup='$vargroup'"
   }
  ]
 },
 "panels": [
  {
   "title": "Meter & Sensor Data",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT t1.value::numeric AS \"value\", t1.\"varkey\", t1.time AS \"time\", '$node' AS node, t1.device, t1.vargroup FROM cityroad_$node t1\r\nWHERE t1.device = '$device' AND t1.vargroup = '$vargroup' AND t1.varkey IN ($varkey) AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT * FROM fn_get_nodes('$network') ORDER BY node"
      }
     ]
    }
   ]
  },
  {
   "title": "Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT t1.network, t1.node, t1.device, t1.vargroup, t1.varkey, t1.value, AGE(t1.timestamp) as age FROM readings t1\r\nWHERE t1.network = '$network'"
      }
     ]
    }
   ]
  }
 ]
}