{
 "title": "Gas Consumption",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "before_base", "query": "1030" },
   { "name": "before_scale", "query": "93" },
   { "name": "after_base", "query": "950" },
   { "name": "after_scale", "query": "40" }
  ]
 },
 "panels": [
  { "title": "Consumption Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distributed Energy",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT (24*0.4*($before_base + ($before_scale * t1.value::numeric))) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name, t1.time AS \"day\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
    },
    {
     "rawSql": "SELECT (24*0.4*($after_base + ($after_scale * t1.value::numeric))) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-now' as name, t1.time AS \"day\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
    },
    {
     "rawSql": "SELECT date_bin('1 day', t1.time, '2023-01-01') as day, (24*(AVG(t1.value::numeric))) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'kw')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() AND device='sitewide'\r\nGROUP BY day, name\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT ((SUM($before_base + ($before_scale * t1.value::numeric)) - SUM($after_base + ($after_scale * t1.value::numeric)))/SUM($before_base + ($before_scale * t1.value::numeric))) AS \"value\",  'pxchange' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    },
    {
     "rawSql": "SELECT (11.11 * (SUM($before_base + ($before_scale * t1.value::numeric)) - SUM($after_base + ($after_scale * t1.value::numeric)))) AS \"value\",  'change' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    },
    {
     "rawSql": "SELECT (0.05 * 11.11 * (SUM($before_base + ($before_scale * t1.value::numeric)) - SUM($after_base + ($after_scale * t1.value::numeric)))) AS \"value\",  'cash' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    },
    {
     "rawSql": "SELECT ((0.00018293 / 0.88) * 11.11 * (SUM($before_base + ($before_scale * t1.value::numeric)) - SUM($after_base + ($after_scale * t1.value::numeric)))) AS \"value\",  'carbon' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    }
   ]
  },
  {
   "title": "Calculated Gas Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT SUM($before_base + ($before_scale * t1.value::numeric)) AS \"value\",  'before' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    },
    {
     "rawSql": "SELECT SUM($after_base + ($after_scale * t1.value::numeric)) AS \"value\",  'after' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    },
    {
     "rawSql": "SELECT (SUM($before_base + ($before_scale * t1.value::numeric)) - SUM($after_base + ($after_scale * t1.value::numeric))) AS \"value\",  'change' as name FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\n"
    }
   ]
  },
  { "type": "ryantxu-ajax-panel", "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 } },
  {
   "title": "Gas Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT date_bin('1 day', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'gasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() AND (t1.value::numeric)>0\r\nGROUP BY day, name\r\n\r\n"
    }
   ]
  },
  {
   "title": "Gas Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT date_bin('1 day', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'totalgasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day, name\r\n\r\n"
    },
    {
     "rawSql": "SELECT date_bin('1 day', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'htotalgasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day, name\r\n\r\n"
    },
    {
     "rawSql": "SELECT ($before_base + ($before_scale * t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name, t1.time AS \"day\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
    },
    {
     "rawSql": "SELECT ($after_base + ($after_scale * t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-now' as name, t1.time AS \"day\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
    }
   ]
  },
  {
   "title": "More",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gas Consumption",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT date_bin('3 week', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"gas\" FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'totalgasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day\r\n\r\n"
      },
      {
       "rawSql": "SELECT date_bin('3 week', t1.time, '2023-01-01') as day, SUM(1030 + (93 * t1.value::numeric)) AS \"hdd\" FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day"
      },
      {
       "rawSql": "SELECT date_bin('3 week', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"gas\" FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'htotalgasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day\r\n\r\n"
      }
     ]
    },
    {
     "title": "Weekly Gas Consumption",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT date_bin('1 week', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"gas\" FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'totalgasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day\r\n\r\n"
      },
      {
       "rawSql": "SELECT date_bin('1 week', t1.time, '2023-01-01') as day, SUM(1030 + (93 * t1.value::numeric)) AS \"hdd\" FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day"
      },
      {
       "rawSql": "SELECT date_bin('1 week', t1.time, '2023-01-01') as day, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"gas\" FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'htotalgasconsumption')  AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nGROUP BY day\r\n\r\n"
      }
     ]
    },
    {
     "title": "Gas Consumption",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT date_bin('6 hour', t1.time, '2023-01-01') as hour, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"gas\",  t1.\"device\" as name FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'gasconsumption') AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() AND (t1.value::numeric)>0\r\nGROUP BY hour, name\r\n\r\n"
      },
      {
       "rawSql": "SELECT date_bin('6 hour', t1.time, '2023-01-01') as hour, (MAX(t1.value::numeric) - MIN(t1.value::numeric)) AS \"kwh\" FROM mystreet_energycentre t1\r\nWHERE (t1.varkey = 'kwh')  AND t1.device = 'sitewide' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() AND (t1.value::numeric)>5000 \r\nGROUP BY hour\r\n\r\n"
      }
     ]
    },
    {
     "title": "Gas Consumption",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT value::numeric, time, device FROM fn_pulses_per_device_per_hour('mystreet_energycentre','meter','gasconsumption',$__timeFrom(), $__timeTo())\r\n\r\n"
      }
     ]
    },
    {
     "title": "Gas Consumption",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT value::numeric, time, device FROM fn_pulses_per_device_per_hour('mystreet_energycentre','meter','gasconsumption',$__timeFrom(), $__timeTo())\r\n\r\n"
      }
     ]
    },
    {
     "title": "Commercial Condensing Boiler Efficiencies",
     "type": "canvas",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 33 }
    },
    {
     "title": "Gas Consumption",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT value::numeric, time FROM fn_counter_to_rate('mystreet_energycentre','system','meter','totalgasconsumption',$__timeFrom(), $__timeTo())\r\n\r\n"
      }
     ]
    },
    {
     "title": "Gas Consumption",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 16, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT t1.value::numeric AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name, t1.time AS \"time\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gas Consumption",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "SELECT ($before_base + ($before_scale * t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-'|| t1.\"varkey\" as name, t1.time AS \"day\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
      },
      {
       "rawSql": "SELECT ($after_base + ($after_scale * t1.value::numeric)) AS \"value\",  t1.\"device\"||'-'||t1.\"vargroup\"||'-now' as name, t1.time AS \"day\", 'energycentre' as node FROM mystreet_energycentre t1\r\nWHERE t1.varkey = 'hDD19' AND t1.time >= $__timeFrom() AND t1.time <= $__timeTo() \r\nORDER BY time ASC "
      }
     ]
    }
   ]
  }
 ]
}