{
 "title": "Information",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": "SELECT DISTINCT network FROM readings"
   },
   {
    "name": "meter",
    "query": "SELECT DISTINCT network||'_'||node||'-'||device FROM readings WHERE varkey='m3h'"
   }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT node,age FROM fn_get_nodes('brunelstreet') ORDER BY node"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM fn_get_nodes('brunelstreet') ORDER BY node"
    }
   ]
  },
  {
   "title": "Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 18, "w": 3, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT node AS node FROM readings WHERE network='$network' ORDER BY node ASC"
      }
     ]
    },
    {
     "title": "Devices",
     "type": "table",
     "gridPos": { "h": 18, "w": 6, "x": 3, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT node,device FROM readings WHERE network='$network' ORDER BY device ASC"
      }
     ]
    },
    {
     "title": "Data",
     "type": "table",
     "gridPos": { "h": 18, "w": 15, "x": 9, "y": 16 },
     "targets": [
      {
       "rawSql": "SELECT node, device, vargroup, varkey, value FROM readings WHERE network = '$network'"
      }
     ]
    }
   ]
  },
  {
   "title": "Heat Meters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heat Meter $meter",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
     "repeat": "meter",
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT fn_weighted_average(lower(split_part($meter, '-', 1)),split_part($meter, '-', 2),'meter','tF','m3h',$__timeFrom(), $__timeTo()) AS vwaft, \r\nfn_weighted_average(lower(split_part($meter, '-', 1)),split_part($meter, '-', 2),'meter','tR','m3h',$__timeFrom(), $__timeTo()) AS vwart,\r\nfn_m3h_to_m3(lower(split_part($meter, '-', 1)),split_part($meter, '-', 2),'meter','m3h',$__timeFrom(), $__timeTo()) AS volume,\r\nfn_m3h_to_m3(lower(split_part($meter, '-', 1)),split_part($meter, '-', 2),'meter','kw',$__timeFrom(), $__timeTo()) AS Energy"
      }
     ]
    }
   ]
  }
 ]
}